image: node:10

before_script:
  - "curl -d 'payload={\"channel\": \"#jenkins\", \"username\": \"GitLab\", \"text\": \"Pipeline $CI_PIPELINE_ID Build $CI_BUILD_ID Ha comenzado\"}' -X POST https://hooks.slack.com/services/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"

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - deploy
deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install            
    - npm install -g @angular/cli
    - npm install -g firebase-tools
    - ng build --output-hashing=all --build-optimizer --aot -c production  
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID @ Hash ${CI_COMMIT_SHA:0:7}" --token $FIREBASE_TOKEN
